### PR TITLE
Feature/data model js architecture pa

### PR DESCRIPTION
**Pull request by Pma913**
This pull request features refactoring made to three files; main.js, index.html and styles.css. All refactors were made to better match rubric requirements. Functionality is still the same.

* this does not address border issue with the idea display cards*

### CODE REVIEW

**Review by sarahcatherine311 — APPROVED** [review]
So glad you figured this part out. Great work!

**Review by RaceOsuna — APPROVED** [review]
id and class updates looks good

**Review by priscillaapaxton — APPROVED** [review]
Great changes! happy we got the html doctype added into the beginning of the html file!

**Review by priscillaapaxton — COMMENTED** [review]
great!

**Pull request merged**
