### PR TITLE
Feat: updated css layout

### PR DESCRIPTION
**Pull request by RaceOsuna**
this feature will include: 

update to idea card borders and scaling to overflow.

### CODE REVIEW

**Comment by priscillaapaxton** [comment]
great final additions !

**Review by sarahcatherine311 — APPROVED** [review]
We finally figured out the borders! hooray!

**Review by priscillaapaxton — APPROVED** [review]
great final additions

**Review by Pma913 — APPROVED** [review]
Great work fixing that border. Adding flex was good idea in the idea-box.

**Pull request merged**
